version: "{build}"

branches:
 only:
  - i5499
  - /try-.*/

environment:
 PY_PYTHON: 2.7-32
 enc_file_key:
  secure: ekOvuyywHuDdGZmRmoj+b3jfrq39A2xlx4RD5ZUGd/8=

init:
 - ps: |
     If ($env:APPVEYOR_REPO_TAG -eq "true") {
      # TODO: Set release version.
      Set-AppveyorBuildVariable "release" "1"
     } else {
      $version = "$env:APPVEYOR_REPO_BRANCH-$env:APPVEYOR_BUILD_NUMBER," + $env:APPVEYOR_REPO_COMMIT.Substring(0, 8)
      Update-AppveyorBuild -Version $version
      Set-AppveyorBuildVariable "release" "0"
     }

clone_depth: 1

install:
 - cd appveyor
 # Decrypt files.
 - openssl enc -aes-256-cbc -d -pass pass:%enc_file_key% -in authenticode.pfx.enc -out authenticode.pfx
 - openssl enc -aes-256-cbc -d -pass pass:%enc_file_key% -in ssh_id_rsa.enc -out ssh_id_rsa
 # Install ssh private key.
 - copy ssh_id_rsa %userprofile%\.ssh\id_rsa
 - cd ..
 - git submodule update --init --depth 1

build_script:
 - py scons.py launcher version=%APPVEYOR_BUILD_VERSION% release=%release% publisher="NV Access Limited" certFile=appveyor\authenticode.pfx certTimestampServer=http://timestamp.digicert.com

artifacts:
 - path: output\*

deploy_script:
 - ps: $artifacts.keys | Foreach-Object { $artifacts[$_]["url"] } | ssh nvaccess@exbi.nvaccess.org appveyorDeploy
