version: "{build}"

branches:
 only:
  - i5499
  - /try-.*/

environment:
 PY_PYTHON: 2.7-32

init:
 - ps: >-
  If ($env:APPVEYOR_REPO_TAG -eq "true") {
   # TODO: Set release version.
   Set-AppveyorBuildVariable "release" "1"
  } else {
   $version = "$env:APPVEYOR_REPO_BRANCH-$env:APPVEYOR_BUILD_NUMBER," + $env:APPVEYOR_REPO_COMMIT.Substring(0, 7)
   Update-AppveyorBuild -Version $version
   Set-AppveyorBuildVariable "release" "0"
  }

install:
 - git submodule update --init

build_script:
 - echo %release%
 #- py scons.py launcher version=%APPVEYOR_BUILD_VERSION% release=%release% publisher="NV Access Limited"

#artifacts:
 #- path: output\*
