version: "{branch}-{build}"

branches:
 only:
  - i5499
  - /try-.*/

environment:
 PY_PYTHON: 2.7-32
 enc_file_key:
  secure: ekOvuyywHuDdGZmRmoj+b3jfrq39A2xlx4RD5ZUGd/8=
 symstore: 'C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\symstore.exe'

init:
 - ps: |
     If ($env:APPVEYOR_REPO_TAG -eq "true") {
      # TODO: Set release version.
      Set-AppveyorBuildVariable "release" "1"
     } else {
      $version = "$env:APPVEYOR_REPO_BRANCH-$env:APPVEYOR_BUILD_NUMBER," + $env:APPVEYOR_REPO_COMMIT.Substring(0, 8)
      Update-AppveyorBuild -Version $version
      Set-AppveyorBuildVariable "release" "0"
     }

clone_depth: 1

install:
 - cd appveyor
 # Decrypt files.
 - openssl enc -aes-256-cbc -d -pass pass:%enc_file_key% -in authenticode.pfx.enc -out authenticode.pfx
 - openssl enc -aes-256-cbc -d -pass pass:%enc_file_key% -in ssh_id_rsa.enc -out ssh_id_rsa
 # Install ssh stuff.
 - copy ssh_id_rsa %userprofile%\.ssh\id_rsa
 - type ssh_known_hosts >> %userprofile%\.ssh\known_hosts
 - cd ..
 - git submodule update --init

build_script:
 - py scons.py launcher version=%APPVEYOR_BUILD_VERSION% release=%release% publisher="NV Access" certFile=appveyor\authenticode.pfx certTimestampServer=http://timestamp.digicert.com
 # Build symbol store.
 - for %p in (source\*.pdb source\lib\*.pdb source\lib64\*.pdb source\synthDrivers\*.pdb) do "%symstore%" add /s symbols /compress -:NOREFS /t NVDA /f %p
 - cd symbols
 - 7z a -tzip -r ..\output\symbols.zip *.pd_
 - cd ..

artifacts:
 - path: output\*

deploy_script:
 - ps: $artifacts.keys | Foreach-Object { $artifacts[$_]["url"] } | ssh nvaccess@exbi.nvaccess.org appveyorDeploy
