version: "{build}"

branches:
 only:
  - i5499

environment:
 PY_PYTHON: 2.7-32

install:
 - git submodule update --init

build_script:
 - py scons.py launcher version=%APPVEYOR_BUILD_VERSION% publisher="NV Access Limited"

artifacts:
 - path: output\*
